name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: nathanfallet
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and publish to Docker Hub
        run: ./gradlew publishImage
